# Generated by Django 5.2.8 on 2025-12-01 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text="The name of the retailer's business.", max_length=255, verbose_name='Company Name')),
                ('business_registration_number', models.CharField(blank=True, help_text='Official business registration number.', max_length=100, null=True, unique=True, verbose_name='Business Registration Number')),
                ('contact_phone', models.CharField(blank=True, help_text='Primary contact phone number.', max_length=20, null=True, verbose_name='Contact Phone')),
                ('address', models.TextField(blank=True, help_text='Business address of the retailer.', null=True, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this retailer account is active.', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The user account associated with this retailer.', on_delete=django.db.models.deletion.CASCADE, related_name='retailer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retailer',
                'verbose_name_plural': 'Retailers',
                'ordering': ['company_name'],
            },
        ),
    ]
