# Generated by Django 5.2.8 on 2025-12-01 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_add_retailer_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='address',
            field=models.TextField(blank=True, help_text="Business address of the retailer's headquarters.", null=True, verbose_name='Address'),
        ),
        migrations.CreateModel(
            name='RetailerBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(help_text='Name or identifier for this branch location.', max_length=255, verbose_name='Branch Name')),
                ('branch_code', models.CharField(blank=True, help_text='Internal code for this branch.', max_length=50, null=True, verbose_name='Branch Code')),
                ('contact_phone', models.CharField(blank=True, help_text='Branch contact phone number.', max_length=20, null=True, verbose_name='Contact Phone')),
                ('address', models.TextField(blank=True, help_text='Physical address of this branch.', null=True, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this branch is active.', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retailer', models.ForeignKey(help_text='The parent retailer this branch belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='users.retailer')),
                ('user', models.OneToOneField(help_text='The user account for this branch to login.', on_delete=django.db.models.deletion.CASCADE, related_name='retailer_branch_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retailer Branch',
                'verbose_name_plural': 'Retailer Branches',
                'ordering': ['retailer', 'branch_name'],
                'unique_together': {('retailer', 'branch_name')},
            },
        ),
    ]
