# Generated by Django 5.2.8 on 2025-11-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0002_alter_contactflowstate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='friendly_name',
            field=models.CharField(blank=True, help_text='A user-friendly name for display purposes. If blank, it will be derived from the name.', max_length=255),
        ),
        migrations.AddField(
            model_name='flow',
            name='trigger_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for advanced triggers, e.g., regex for data extraction. Example: {"extraction_regex": "\\"(.*?)\\"", "context_variable": "product_interest"}'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='name',
            field=models.CharField(help_text='Unique name for this flow (used as an identifier).', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='flowstep',
            name='step_type',
            field=models.CharField(choices=[('send_message', 'Send Message'), ('question', 'Ask Question'), ('condition', 'Conditional Branch'), ('action', 'Perform Action'), ('wait_for_reply', 'Wait for Reply'), ('end_flow', 'End Flow'), ('start_flow_node', 'Start Flow Node'), ('human_handover', 'Handover to Human Agent'), ('switch_flow', 'Switch to Another Flow')], max_length=50),
        ),
    ]
