# Generated by Django 5.2.9 on 2025-12-02 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_contact_associated_app_config_and_more'),
        ('flows', '0002_alter_contactflowstate_unique_together_and_more'),
        ('meta_integration', '0002_metaappconfig_app_secret_metaappconfig_catalog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='friendly_name',
            field=models.CharField(blank=True, help_text='A user-friendly name for display purposes. If blank, it will be derived from the name.', max_length=255),
        ),
        migrations.AddField(
            model_name='flow',
            name='trigger_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for advanced triggers, e.g., regex for data extraction. Example: {"extraction_regex": "\\"(.*?)\\"", "context_variable": "product_interest"}'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='name',
            field=models.CharField(help_text='Unique name for this flow (used as an identifier).', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='flowstep',
            name='step_type',
            field=models.CharField(choices=[('send_message', 'Send Message'), ('question', 'Ask Question'), ('condition', 'Conditional Branch'), ('action', 'Perform Action'), ('wait_for_reply', 'Wait for Reply'), ('end_flow', 'End Flow'), ('start_flow_node', 'Start Flow Node'), ('human_handover', 'Handover to Human Agent'), ('switch_flow', 'Switch to Another Flow')], max_length=50),
        ),
        migrations.CreateModel(
            name='WhatsAppFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for this WhatsApp flow (used as an identifier).', max_length=255, unique=True)),
                ('friendly_name', models.CharField(blank=True, help_text='A user-friendly name for display purposes.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A brief description of what this flow does.', null=True)),
                ('flow_id', models.CharField(blank=True, db_index=True, help_text='The flow ID returned by Meta after syncing.', max_length=100, null=True, unique=True)),
                ('flow_json', models.JSONField(help_text="The WhatsApp Flow JSON definition conforming to Meta's Flow JSON schema.")),
                ('sync_status', models.CharField(choices=[('draft', 'Draft'), ('syncing', 'Syncing with Meta'), ('published', 'Published'), ('deprecated', 'Deprecated'), ('error', 'Sync Error')], db_index=True, default='draft', help_text='Current sync status with Meta.', max_length=20)),
                ('sync_error', models.TextField(blank=True, help_text='Error message if sync failed.', null=True)),
                ('version', models.IntegerField(default=1, help_text='Version number of this flow definition.')),
                ('is_active', models.BooleanField(default=False, help_text='Is this flow currently active and can be triggered?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful sync with Meta.', null=True)),
                ('flow_definition', models.ForeignKey(blank=True, help_text='Optional link to the traditional flow definition this replaces.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_flows', to='flows.flow')),
                ('meta_app_config', models.ForeignKey(help_text='The Meta app configuration this flow is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_flows', to='meta_integration.metaappconfig')),
            ],
            options={
                'verbose_name': 'WhatsApp Flow',
                'verbose_name_plural': 'WhatsApp Flows',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppFlowResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_token', models.CharField(help_text='The flow token from Meta that identifies this flow session.', max_length=255)),
                ('response_data', models.JSONField(help_text='The complete response payload from the user, including all form data.')),
                ('is_processed', models.BooleanField(db_index=True, default=False, help_text='Whether this response has been processed by the system.')),
                ('processing_notes', models.TextField(blank=True, help_text='Notes or results from processing this response.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when this response was processed.', null=True)),
                ('contact', models.ForeignKey(help_text='The contact who submitted this flow response.', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_flow_responses', to='conversations.contact')),
                ('whatsapp_flow', models.ForeignKey(help_text='The WhatsApp flow this response is for.', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='flows.whatsappflow')),
            ],
            options={
                'verbose_name': 'WhatsApp Flow Response',
                'verbose_name_plural': 'WhatsApp Flow Responses',
                'ordering': ['-created_at'],
            },
        ),
    ]
