# Generated by Django 5.2.9 on 2025-12-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google_gemini', 'Google Gemini')], max_length=50, unique=True)),
                ('api_key', models.CharField(help_text='The API key for the provider.', max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='Only one provider of each type should be active at a time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_limit_limit', models.IntegerField(blank=True, help_text='The request limit per minute for this key.', null=True)),
                ('rate_limit_remaining', models.IntegerField(blank=True, help_text='The number of remaining requests for the current window.', null=True)),
                ('rate_limit_reset_time', models.DateTimeField(blank=True, help_text='The time when the rate limit window resets.', null=True)),
            ],
        ),
    ]
