# Generated by Django 5.2.8 on 2025-11-12 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_contact_intervention_requested_at_and_more'),
        ('flows', '0003_add_barcode_fields'),
        ('meta_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='associated_app_config',
            field=models.ForeignKey(blank=True, help_text='The Meta App Configuration this contact is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta_integration.metaappconfig'),
        ),
        migrations.AddField(
            model_name='contact',
            name='conversation_context',
            field=models.JSONField(blank=True, default=dict, help_text='Stores context for the current conversation, e.g., AI persona or history.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='conversation_mode',
            field=models.CharField(choices=[('flow', 'Flow-based Conversation'), ('ai_troubleshooting', 'AI Troubleshooting Mode')], default='flow', help_text='The current conversation mode for this contact.', max_length=30),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link to a system user if this contact represents an admin/agent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='app_config',
            field=models.ForeignKey(blank=True, help_text='The Meta App Configuration used for sending/receiving this message.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meta_integration.metaappconfig'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation_id_from_meta',
            field=models.CharField(blank=True, help_text='The conversation ID from Meta for this message.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_system_notification',
            field=models.BooleanField(default=False, help_text='True if this is a system-generated notification to an admin.'),
        ),
        migrations.AddField(
            model_name='message',
            name='pricing_model_from_meta',
            field=models.CharField(blank=True, help_text="The pricing model from Meta (e.g., 'CBP').", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='related_incoming_message',
            field=models.ForeignKey(blank=True, help_text='The incoming message that this message is a reply to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='conversations.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='triggered_by_flow_step',
            field=models.ForeignKey(blank=True, help_text='The flow step that triggered this outgoing message.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_messages', to='flows.flowstep'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('pending_dispatch', 'Pending Dispatch'), ('sent', 'Sent to Meta'), ('delivered', 'Delivered to User'), ('read', 'Read by User'), ('failed', 'Failed to Send'), ('deleted', 'Deleted'), ('received', 'Received')], default='pending_dispatch', help_text='Status of the message.', max_length=20),
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='An internal name for this broadcast campaign.', max_length=255)),
                ('template_name', models.CharField(help_text='The name of the Meta template used for this broadcast.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('pending_dispatch_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broadcast',
                'verbose_name_plural': 'Broadcasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_dispatch', 'Pending Dispatch'), ('sent', 'Sent to Meta'), ('delivered', 'Delivered to User'), ('read', 'Read by User'), ('failed', 'Failed to Send'), ('deleted', 'Deleted'), ('received', 'Received')], default='pending_dispatch', max_length=20)),
                ('status_timestamp', models.DateTimeField(blank=True, null=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='conversations.broadcast')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts_received', to='conversations.contact')),
                ('message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_recipient', to='conversations.message')),
            ],
            options={
                'ordering': ['broadcast', 'contact'],
                'unique_together': {('broadcast', 'contact')},
            },
        ),
    ]
