# Generated by Django 5.2.9 on 2025-12-02 19:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('customer_data', '0003_interaction_jobcard_loanapplication_order_orderitem_and_more'),
        ('products_and_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Manufacturer Name')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email')),
                ('user', models.OneToOneField(blank=True, help_text="The user account that can access this manufacturer's dashboard.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_type', models.CharField(choices=[('installer', 'Installer'), ('factory', 'Factory'), ('callout', 'Callout')], default='installer', max_length=20, verbose_name='Technician Type')),
                ('specialization', models.CharField(blank=True, help_text='e.g., Solar, Plumbing, Electrical', max_length=255, verbose_name='Specialization')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='The manufacturer this technician is associated with (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technicians', to='warranty.manufacturer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Installer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installer_profile', to='warranty.technician')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='warranty.technician')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.CharField(max_length=36)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('technician', models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Warranty Start Date')),
                ('end_date', models.DateField(verbose_name='Warranty End Date')),
                ('manufacturer_email', models.EmailField(blank=True, help_text='Email for sending warranty claim notifications to the product manufacturer.', max_length=254, null=True, verbose_name='Manufacturer Email')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('void', 'Void')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associated_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranties', to='customer_data.order')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='customer_data.customerprofile')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warranties', to='warranty.manufacturer')),
                ('serialized_item', models.OneToOneField(help_text='The specific serialized item that this warranty covers.', on_delete=django.db.models.deletion.CASCADE, related_name='warranty', to='products_and_services.serializeditem')),
            ],
            options={
                'verbose_name': 'Warranty',
                'verbose_name_plural': 'Warranties',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Claim ID')),
                ('description_of_fault', models.TextField(verbose_name='Description of Fault')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('replaced', 'Replaced'), ('closed', 'Closed')], db_index=True, default='pending', max_length=20, verbose_name='Claim Status')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='Resolution Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='warranty.warranty')),
            ],
            options={
                'verbose_name': 'Warranty Claim',
                'verbose_name_plural': 'Warranty Claims',
                'ordering': ['-created_at'],
            },
        ),
    ]
