# Generated by Django 5.2.9 on 2025-12-03 08:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_data', '0004_installationrequest_technicians_interaction_agent_and_more'),
        ('products_and_services', '0001_initial'),
        ('warranty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='warranty.manufacturer'),
        ),
        migrations.AddField(
            model_name='serializeditem',
            name='order_item',
            field=models.ForeignKey(blank=True, help_text='The order line item this physical unit is assigned to fulfill.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_items', to='customer_data.orderitem'),
        ),
        migrations.CreateModel(
            name='ItemLocationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_location', models.CharField(blank=True, choices=[('warehouse', 'Warehouse'), ('customer', 'Customer Location'), ('manufacturer', 'Manufacturer Facility'), ('technician', 'Technician/Service Center'), ('in_transit', 'In Transit'), ('outsourced', 'Outsourced Service Provider'), ('retail', 'Retail Store'), ('disposed', 'Disposed/Scrapped')], help_text='Previous location (null for initial entry)', max_length=20, null=True, verbose_name='From Location')),
                ('to_location', models.CharField(choices=[('warehouse', 'Warehouse'), ('customer', 'Customer Location'), ('manufacturer', 'Manufacturer Facility'), ('technician', 'Technician/Service Center'), ('in_transit', 'In Transit'), ('outsourced', 'Outsourced Service Provider'), ('retail', 'Retail Store'), ('disposed', 'Disposed/Scrapped')], help_text='New location', max_length=20, verbose_name='To Location')),
                ('transfer_reason', models.CharField(choices=[('sale', 'Sale to Customer'), ('repair', 'Repair/Service'), ('warranty_claim', 'Warranty Claim'), ('return', 'Customer Return'), ('transfer', 'Internal Transfer'), ('collection', 'Collection from Customer'), ('delivery', 'Delivery to Customer'), ('outsource', 'Sent for Outsourcing'), ('installation', 'Installation at Customer Site'), ('stock_receipt', 'Stock Receipt'), ('disposal', 'Item Disposal')], help_text='Reason for the location change', max_length=20, verbose_name='Transfer Reason')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this transfer', verbose_name='Notes')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('from_holder', models.ForeignKey(blank=True, help_text='Previous holder of the item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_from_items', to=settings.AUTH_USER_MODEL)),
                ('related_job_card', models.ForeignKey(blank=True, help_text='Related job card, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_location_changes', to='customer_data.jobcard')),
                ('related_order', models.ForeignKey(blank=True, help_text='Related sales order, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_location_changes', to='customer_data.order')),
                ('related_warranty_claim', models.ForeignKey(blank=True, help_text='Related warranty claim, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_location_changes', to='warranty.warrantyclaim')),
                ('serialized_item', models.ForeignKey(help_text='The item whose location is being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='products_and_services.serializeditem')),
                ('to_holder', models.ForeignKey(blank=True, help_text='New holder of the item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_to_items', to=settings.AUTH_USER_MODEL)),
                ('transferred_by', models.ForeignKey(help_text='User who initiated this transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_transfers_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Location History',
                'verbose_name_plural': 'Item Location Histories',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'serialized_item'], name='products_an_timesta_9c510b_idx'), models.Index(fields=['to_location', '-timestamp'], name='products_an_to_loca_c60415_idx')],
            },
        ),
    ]
