# Generated by Django - Add Meta sync tracking fields to Product model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_and_services', '0001_initial'),  # Depends on existing initial migration
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_sync_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of times sync to Meta Catalog has been attempted', verbose_name='Meta Sync Attempts'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_sync_last_error',
            field=models.TextField(blank=True, help_text='Last error message from Meta API sync attempt', null=True, verbose_name='Last Meta Sync Error'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_sync_last_attempt',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last sync attempt', null=True, verbose_name='Last Meta Sync Attempt'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_sync_last_success',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful sync', null=True, verbose_name='Last Meta Sync Success'),
        ),
    ]
