# Generated by Django 5.2.8 on 2025-11-12 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products_and_services', '0001_add_barcode_fields'),
        ('warranty', '0001_add_barcode_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='warranty.manufacturer'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent_product',
            field=models.ForeignKey(blank=True, help_text='If this is a module, this links to the main software product.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='products_and_services.product'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Parent category for creating a hierarchy (e.g., 'Software' -> 'Accounting').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products_and_services.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products_and_services.productcategory'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products_and_services.product'),
        ),
        migrations.AddField(
            model_name='serializeditem',
            name='product',
            field=models.ForeignKey(help_text='The generic product that this item is an instance of.', on_delete=django.db.models.deletion.PROTECT, related_name='serialized_items', to='products_and_services.product'),
        ),
    ]
