# Generated by Django 5.2.8 on 2025-11-12 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_add_barcode_fields'),
        ('meta_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaappconfig',
            name='app_secret',
            field=models.CharField(blank=True, help_text='The App Secret from the Meta App Dashboard, used for verifying webhook signature. Recommended.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metaappconfig',
            name='catalog_id',
            field=models.CharField(blank=True, help_text='The ID of the WhatsApp Catalog to use for this configuration.', max_length=50, null=True, verbose_name='WhatsApp Catalog ID'),
        ),
        migrations.AddField(
            model_name='webhookeventlog',
            name='message',
            field=models.ForeignKey(blank=True, help_text='The Message object created from this event, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='conversations.message'),
        ),
        migrations.AlterField(
            model_name='metaappconfig',
            name='phone_number_id',
            field=models.CharField(help_text='The Phone Number ID from which messages will be sent. Must be unique, as this is used to identify the configuration for incoming webhooks.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='webhookeventlog',
            name='event_identifier',
            field=models.CharField(blank=True, db_index=True, help_text='A non-unique identifier for the event (e.g., wamid for messages).', max_length=255, null=True),
        ),
    ]
