# Generated by Django 5.2.8 on 2025-12-01 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the administrator.', max_length=100)),
                ('email', models.EmailField(help_text='Email address to send notifications to.', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to disable notifications for this recipient without deleting them.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Email Recipient',
                'verbose_name_plural': 'Admin Email Recipients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A friendly name for the email account, e.g., 'Sales Inbox'", max_length=100)),
                ('imap_host', models.CharField(max_length=255)),
                ('imap_user', models.CharField(max_length=255)),
                ('imap_password', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=993, help_text='IMAP server port. Default is 993 for SSL.')),
                ('ssl_protocol', models.CharField(choices=[('auto', 'Auto (default)'), ('tls_v1_2', 'TLSv1.2'), ('tls_v1_3', 'TLSv1.3')], default='auto', help_text='Specify the SSL/TLS protocol version.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable fetching from this account.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('email_date', models.DateTimeField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('extracted_data', models.JSONField(blank=True, help_text='Structured data extracted by AI model.', null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='email_integration.emailaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ParsedInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_invoice', to='email_integration.emailattachment')),
            ],
        ),
    ]
