# Generated by Django 5.2.9 on 2025-12-02 19:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_contact_associated_app_config_and_more'),
        ('customer_data', '0002_customerprofile_acquisition_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('whatsapp', 'WhatsApp Message'), ('meeting', 'Meeting'), ('note', 'Internal Note'), ('other', 'Other')], default='note', max_length=50, verbose_name='Interaction Type')),
                ('notes', models.TextField(help_text='A summary of the interaction, key points, and next steps.', verbose_name='Notes / Summary')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the interaction occurred.', verbose_name='Interaction Time')),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_card_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Job Card Number')),
                ('reported_fault', models.TextField(blank=True, null=True, verbose_name='Reported Fault')),
                ('is_under_warranty', models.BooleanField(default=False, verbose_name='Under Warranty')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Creation Date')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('awaiting_parts', 'Awaiting Parts'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=50, verbose_name='Status')),
                ('job_card_details', models.JSONField(blank=True, help_text='Raw JSON data extracted from the document.', null=True, verbose_name='Extracted Job Card Details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Card',
                'verbose_name_plural': 'Job Cards',
                'ordering': ['-creation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('national_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='National ID')),
                ('loan_type', models.CharField(choices=[('cash_loan', 'Cash Loan'), ('product_loan', 'Product Loan')], max_length=20, verbose_name='Loan Type')),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Other')], max_length=20, verbose_name='Employment Status')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monthly Income (USD)')),
                ('requested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Requested Amount (USD)')),
                ('product_of_interest', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product of Interest')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress')], db_index=True, default='pending_review', max_length=20, verbose_name='Application Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loan Application',
                'verbose_name_plural': 'Loan Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, help_text='Unique order number or reference for this order.', max_length=100, null=True, unique=True, verbose_name='Order Number')),
                ('name', models.CharField(blank=True, help_text="e.g., '5kVA Solar Kit for Mr. Smith'", max_length=255, null=True, verbose_name='Order Name')),
                ('stage', models.CharField(choices=[('prospecting', 'Prospecting'), ('qualification', 'Qualification'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], db_index=True, default='prospecting', max_length=50, verbose_name='Stage')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('refunded', 'Refunded'), ('not_applicable', 'Not Applicable')], db_index=True, default='pending', max_length=50, verbose_name='Payment Status')),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('flow', 'Flow Automation'), ('email_import', 'Email Import'), ('api', 'API Integration')], db_index=True, default='manual', help_text='How this order was created in the system.', max_length=50, verbose_name='Source')),
                ('invoice_details', models.JSONField(blank=True, help_text='Raw JSON data extracted from the invoice attachment.', null=True, verbose_name='Invoice Details')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='The estimated or actual value of the deal.', max_digits=12, null=True, verbose_name='Amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='Expected Close Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price of the product at the time the order was placed.', max_digits=12, verbose_name='Unit Price')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='The total amount for this line item (quantity * unit_price + tax).', max_digits=12, verbose_name='Total Amount')),
                ('units_assigned', models.PositiveIntegerField(default=0, help_text='Number of SerializedItems assigned to this order line.', verbose_name='Units Assigned')),
                ('is_fully_assigned', models.BooleanField(db_index=True, default=False, help_text='Whether all units for this line item have been assigned.', verbose_name='Fully Assigned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('awaiting_delivery', 'Awaiting Delivery'), ('delivered', 'Delivered')], db_index=True, default='pending', max_length=50, verbose_name='Payment Status')),
                ('payment_method', models.CharField(default='paynow', max_length=50, verbose_name='Payment Method')),
                ('provider_transaction_id', models.CharField(blank=True, db_index=True, help_text='The unique ID for this transaction from the payment provider (e.g., Paynow poll URL or reference).', max_length=255, null=True, verbose_name='Provider Transaction ID')),
                ('poll_url', models.CharField(blank=True, help_text='The URL to poll for transaction status updates from Paynow.', max_length=255, null=True, verbose_name='Paynow Poll URL')),
                ('provider_response', models.JSONField(blank=True, default=dict, help_text='The last raw response received from the payment provider.', verbose_name='Provider Response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteAssessmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Assessment ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('assessed', 'Assessed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('assessment_type', models.CharField(choices=[('starlink', 'Starlink'), ('commercial_solar', 'Commercial Solar System'), ('hybrid_starlink_solar', 'Hybrid (Starlink + Solar)'), ('custom_furniture', 'Custom Furniture'), ('other', 'Other')], db_index=True, default='other', help_text='Purpose of the site assessment e.g. Starlink, Commercial Solar System, Hybrid, Custom Furniture.', max_length=50, verbose_name='Assessment Type')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name')),
                ('address', models.TextField(verbose_name='Assessment Address')),
                ('contact_info', models.CharField(max_length=255, verbose_name='Contact Info')),
                ('preferred_day', models.CharField(max_length=255, verbose_name='Preferred Day')),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS latitude coordinate of the site', max_digits=10, null=True, verbose_name='Location Latitude')),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS longitude coordinate of the site', max_digits=10, null=True, verbose_name='Location Longitude')),
                ('location_name', models.CharField(blank=True, help_text='Name of the location (if provided by WhatsApp)', max_length=500, null=True, verbose_name='Location Name')),
                ('location_address', models.TextField(blank=True, help_text='Address associated with the shared location pin', null=True, verbose_name='Location Address from Pin')),
                ('location_url', models.URLField(blank=True, help_text='Google Maps or similar URL for the location', max_length=500, null=True, verbose_name='Location URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolarCleaningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('quoted', 'Quoted'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('roof_type', models.CharField(choices=[('tile', 'Tile Roof'), ('ibr_metal', 'IBR / Metal Sheet'), ('flat_concrete', 'Flat Concrete'), ('shingle', 'Shingle Roof'), ('other', 'Other / Not Sure')], max_length=50)),
                ('panel_type', models.CharField(choices=[('monocrystalline', 'Monocrystalline'), ('polycrystalline', 'Polycrystalline'), ('not_sure', 'Not Sure')], max_length=50)),
                ('panel_count', models.PositiveIntegerField(help_text='The number of solar panels to be cleaned.')),
                ('preferred_date', models.CharField(help_text="Customer's preferred date as a string.", max_length=100)),
                ('availability', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=20)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solar Cleaning Request',
                'verbose_name_plural': 'Solar Cleaning Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'ordering': ['-last_interaction_date', '-updated_at'], 'verbose_name': 'Customer Profile', 'verbose_name_plural': 'Customer Profiles'},
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='last_updated_from_conversation',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='lifecycle_stage',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='secondary_phone_number',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text='The sales or support agent assigned to this customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='last_interaction_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the last recorded interaction with this customer.', null=True, verbose_name='Last Interaction Date'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='lead_score',
            field=models.IntegerField(db_index=True, default=0, help_text='A score to qualify leads, can be updated by flow actions.', verbose_name='Lead Score'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='lead_status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('on_hold', 'On Hold')], db_index=True, default='new', help_text='The current stage of the customer in the sales pipeline.', max_length=50, verbose_name='Lead Status'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='potential_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated value of the deal or lifetime value of the customer.', max_digits=12, null=True, verbose_name='Potential Value'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Role/Title'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked auth user for portal access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='acquisition_source',
            field=models.CharField(blank=True, help_text="How this customer was acquired, e.g., 'Website Form', 'Cold Call', 'Referral'", max_length=150, null=True, verbose_name='Acquisition Source'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='contact',
            field=models.OneToOneField(help_text='The contact this customer profile belongs to.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer_profile', serialize=False, to='conversations.contact'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='custom_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible field for storing custom data collected via forms or integrations.'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='notes',
            field=models.TextField(blank=True, help_text='General notes about the customer, their needs, or past interactions.', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Descriptive tags for segmentation, e.g., ['high-priority', 'tech-industry', 'follow-up']", verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='InstallationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('installation_type', models.CharField(choices=[('starlink', 'Starlink Installation'), ('solar', 'Solar Panel Installation'), ('hybrid', 'Hybrid (Starlink + Solar)'), ('custom_furniture', 'Custom Furniture Installation'), ('residential', 'Residential (Legacy)'), ('commercial', 'Commercial (Legacy)')], db_index=True, max_length=50)),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Order Number')),
                ('assessment_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Assessment Number')),
                ('full_name', models.CharField(help_text='Full name of the contact requesting the installation', max_length=255, verbose_name='Contact Full Name')),
                ('address', models.TextField(verbose_name='Installation Address')),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS latitude coordinate of the installation site', max_digits=10, null=True, verbose_name='Location Latitude')),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS longitude coordinate of the installation site', max_digits=10, null=True, verbose_name='Location Longitude')),
                ('location_name', models.CharField(blank=True, help_text='Name of the location (if provided by WhatsApp)', max_length=500, null=True, verbose_name='Location Name')),
                ('location_address', models.TextField(blank=True, help_text='Address associated with the shared location pin', null=True, verbose_name='Location Address from Pin')),
                ('location_url', models.URLField(blank=True, help_text='Google Maps or similar URL for the location', max_length=500, null=True, verbose_name='Location URL')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('preferred_datetime', models.CharField(max_length=255, verbose_name='Preferred Date/Time')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Contact Phone')),
                ('branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Branch')),
                ('sales_person_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sales Person Name')),
                ('availability', models.CharField(blank=True, max_length=50, null=True, verbose_name='Availability')),
                ('alternative_contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alternative Contact Name')),
                ('alternative_contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alternative Contact Number')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Installation Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_requests', to='customer_data.customerprofile', verbose_name='Customer Profile')),
            ],
        ),
    ]
