# Generated by Django 5.2.9 on 2025-12-02 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_data', '0003_interaction_jobcard_loanapplication_order_orderitem_and_more'),
        ('products_and_services', '0001_initial'),
        ('warranty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='installationrequest',
            name='technicians',
            field=models.ManyToManyField(blank=True, help_text='The technician(s) assigned to this installation.', related_name='installation_requests', to='warranty.technician'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='The agent who had the interaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interaction',
            name='customer',
            field=models.ForeignKey(help_text='The customer this interaction is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='customer_data.customerprofile'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='customer_data.customerprofile'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='serialized_item',
            field=models.ForeignKey(blank=True, help_text='The specific serialized item that this job card is for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='products_and_services.serializeditem'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='warranty.technician'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='warranty_claim',
            field=models.OneToOneField(blank=True, help_text='The warranty claim that this job card is for, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_card', to='warranty.warrantyclaim'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='customer',
            field=models.ForeignKey(help_text='The customer profile of the applicant.', on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='customer_data.customerprofile'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customer_data.customerprofile'),
        ),
        migrations.AddField(
            model_name='installationrequest',
            name='associated_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_requests', to='customer_data.order', verbose_name='Associated Order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customer_data.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products_and_services.product'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='The customer who made the payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='customer_data.customerprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, help_text='The sales order this payment is for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='customer_data.order'),
        ),
        migrations.AddField(
            model_name='siteassessmentrequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_requests', to='customer_data.customerprofile'),
        ),
        migrations.AddField(
            model_name='solarcleaningrequest',
            name='customer',
            field=models.ForeignKey(help_text='The customer profile of the contact who made the request.', on_delete=django.db.models.deletion.CASCADE, related_name='solar_cleaning_requests', to='customer_data.customerprofile'),
        ),
    ]
